// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import "frb_generated.dart";
import "package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart";
import "progresses.dart";
import "types.dart";

// These functions are ignored because they are not marked as `pub`: `level_str`, `new`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CoreLayer`, `CoreVisitor`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `on_event`, `record_debug`

Stream<LogEntry> initTracing() => RustLib.instance.api.crateFfiInitTracing();

Future<void> send({
  required List<String> paths,
  String? addr,
  String? relay,
  required RustStreamSink<List<ProgressState>> stream,
  required RustStreamSink<SendResult> result,
}) => RustLib.instance.api.crateFfiSend(
  paths: paths,
  addr: addr,
  relay: relay,
  stream: stream,
  result: result,
);

Future<void> cancelSend({required String ticket}) =>
    RustLib.instance.api.crateFfiCancelSend(ticket: ticket);

Future<void> receive({
  required String ticket,
  required String downloadDir,
  String? relay,
  required RustStreamSink<List<ProgressState>> stream,
  required RustStreamSink<ReceiveResult> result,
}) => RustLib.instance.api.crateFfiReceive(
  ticket: ticket,
  downloadDir: downloadDir,
  relay: relay,
  stream: stream,
  result: result,
);

Future<void> acceptReceive({required String ticket}) =>
    RustLib.instance.api.crateFfiAcceptReceive(ticket: ticket);

Future<void> rejectReceive({required String ticket}) =>
    RustLib.instance.api.crateFfiRejectReceive(ticket: ticket);

Future<void> cancelReceive({required String ticket}) =>
    RustLib.instance.api.crateFfiCancelReceive(ticket: ticket);

Future<Uint8List> qrReader({required List<int> image}) =>
    RustLib.instance.api.crateFfiQrReader(image: image);

Future<Map<String, String>> getAddrs() =>
    RustLib.instance.api.crateFfiGetAddrs();
