// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import "dart:async";
import "dart:convert";
import "ffi.dart";
import "frb_generated.dart";
import "frb_generated.io.dart"
    if (dart.library.js_interop) "frb_generated.web.dart";
import "package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart";
import "progresses.dart";
import "types.dart";

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateFfiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => "2.12.0";

  @override
  int get rustContentHash => 553960083;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: "drop_plus_core",
        ioDirectory: "core/target/release/",
        webPrefix: "pkg/",
        wasmBindgenName: "wasm_bindgen",
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateFfiAcceptReceive({required String ticket});

  Future<void> crateFfiCancelReceive({required String ticket});

  Future<void> crateFfiCancelSend({required String ticket});

  Future<Map<String, String>> crateFfiGetAddrs();

  Future<void> crateFfiInitApp();

  Stream<LogEntry> crateFfiInitTracing();

  Future<Uint8List> crateFfiQrReader({required List<int> image});

  Future<void> crateFfiReceive({
    required String ticket,
    required String downloadDir,
    String? relay,
    required RustStreamSink<List<ProgressState>> stream,
    required RustStreamSink<ReceiveResult> result,
  });

  Future<void> crateFfiRejectReceive({required String ticket});

  Future<void> crateFfiSend({
    required List<String> paths,
    String? addr,
    String? relay,
    required RustStreamSink<List<ProgressState>> stream,
    required RustStreamSink<SendResult> result,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateFfiAcceptReceive({required String ticket}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(ticket, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFfiAcceptReceiveConstMeta,
        argValues: [ticket],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiAcceptReceiveConstMeta => const TaskConstMeta(
    debugName: "accept_receive(dart_style=acceptReceive)",
    argNames: ["ticket"],
  );

  @override
  Future<void> crateFfiCancelReceive({required String ticket}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(ticket, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFfiCancelReceiveConstMeta,
        argValues: [ticket],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiCancelReceiveConstMeta => const TaskConstMeta(
    debugName: "cancel_receive(dart_style=cancelReceive)",
    argNames: ["ticket"],
  );

  @override
  Future<void> crateFfiCancelSend({required String ticket}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(ticket, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFfiCancelSendConstMeta,
        argValues: [ticket],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiCancelSendConstMeta => const TaskConstMeta(
    debugName: "cancel_send(dart_style=cancelSend)",
    argNames: ["ticket"],
  );

  @override
  Future<Map<String, String>> crateFfiGetAddrs() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_Map_String_String_None,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFfiGetAddrsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiGetAddrsConstMeta => const TaskConstMeta(
    debugName: "get_addrs(dart_style=getAddrs)",
    argNames: [],
  );

  @override
  Future<void> crateFfiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateFfiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Stream<LogEntry> crateFfiInitTracing() {
    final stream = RustStreamSink<LogEntry>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_log_entry_Sse(stream, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 6,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateFfiInitTracingConstMeta,
          argValues: [stream],
          apiImpl: this,
        ),
      ),
    );
    return stream.stream;
  }

  TaskConstMeta get kCrateFfiInitTracingConstMeta => const TaskConstMeta(
    debugName: "init_tracing(dart_style=initTracing)",
    argNames: ["stream"],
  );

  @override
  Future<Uint8List> crateFfiQrReader({required List<int> image}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(image, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFfiQrReaderConstMeta,
        argValues: [image],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiQrReaderConstMeta => const TaskConstMeta(
    debugName: "qr_reader(dart_style=qrReader)",
    argNames: ["image"],
  );

  @override
  Future<void> crateFfiReceive({
    required String ticket,
    required String downloadDir,
    String? relay,
    required RustStreamSink<List<ProgressState>> stream,
    required RustStreamSink<ReceiveResult> result,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(ticket, serializer);
          sse_encode_String(downloadDir, serializer);
          sse_encode_opt_String(relay, serializer);
          sse_encode_StreamSink_list_progress_state_Sse(stream, serializer);
          sse_encode_StreamSink_receive_result_Sse(result, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFfiReceiveConstMeta,
        argValues: [ticket, downloadDir, relay, stream, result],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiReceiveConstMeta => const TaskConstMeta(
    debugName: "receive(dart_style=receive)",
    argNames: ["ticket", "downloadDir", "relay", "stream", "result"],
  );

  @override
  Future<void> crateFfiRejectReceive({required String ticket}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(ticket, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFfiRejectReceiveConstMeta,
        argValues: [ticket],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiRejectReceiveConstMeta => const TaskConstMeta(
    debugName: "reject_receive(dart_style=rejectReceive)",
    argNames: ["ticket"],
  );

  @override
  Future<void> crateFfiSend({
    required List<String> paths,
    String? addr,
    String? relay,
    required RustStreamSink<List<ProgressState>> stream,
    required RustStreamSink<SendResult> result,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(paths, serializer);
          sse_encode_opt_String(addr, serializer);
          sse_encode_opt_String(relay, serializer);
          sse_encode_StreamSink_list_progress_state_Sse(stream, serializer);
          sse_encode_StreamSink_send_result_Sse(result, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateFfiSendConstMeta,
        argValues: [paths, addr, relay, stream, result],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiSendConstMeta => const TaskConstMeta(
    debugName: "send(dart_style=send)",
    argNames: ["paths", "addr", "relay", "stream", "result"],
  );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(
      dco_decode_list_record_string_string(
        raw,
      ).map((e) => MapEntry(e.$1, e.$2)),
    );
  }

  @protected
  RustStreamSink<List<ProgressState>>
  dco_decode_StreamSink_list_progress_state_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<LogEntry> dco_decode_StreamSink_log_entry_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<ReceiveResult> dco_decode_StreamSink_receive_result_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<SendResult> dco_decode_StreamSink_send_result_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BlobInfo dco_decode_blob_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception("unexpected arr length: expect 2 but see ${arr.length}");
    return BlobInfo(
      name: dco_decode_String(arr[0]),
      size: dco_decode_u_64(arr[1]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<BlobInfo> dco_decode_list_blob_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_blob_info).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ProgressState> dco_decode_list_progress_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_progress_state).toList();
  }

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_string).toList();
  }

  @protected
  LogEntry dco_decode_log_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception("unexpected arr length: expect 4 but see ${arr.length}");
    return LogEntry(
      time: dco_decode_u_64(arr[0]),
      level: dco_decode_String(arr[1]),
      target: dco_decode_String(arr[2]),
      data: dco_decode_Map_String_String_None(arr[3]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  Phase dco_decode_phase(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return Phase_Importing(name: dco_decode_String(raw[1]));
      case 1:
        return Phase_Uploading(
          endpoint: dco_decode_String(raw[1]),
          isCompleted: dco_decode_bool(raw[2]),
          isFailed: dco_decode_bool(raw[3]),
        );
      case 2:
        return const Phase_Pending();
      case 3:
        return const Phase_Connecting();
      case 4:
        return const Phase_Validating();
      case 5:
        return const Phase_Downloading();
      case 6:
        return Phase_Exporting(name: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  ProgressState dco_decode_progress_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception("unexpected arr length: expect 3 but see ${arr.length}");
    return ProgressState(
      phase: dco_decode_phase(arr[0]),
      position: dco_decode_u_64(arr[1]),
      length: dco_decode_opt_box_autoadd_u_64(arr[2]),
    );
  }

  @protected
  ReceiveResult dco_decode_receive_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return ReceiveResult_Pending(files: dco_decode_list_blob_info(raw[1]));
      case 1:
        return ReceiveResult_Ok(
          totalFiles: dco_decode_u_64(raw[1]),
          payloadSize: dco_decode_u_64(raw[2]),
          elapsedSecs: dco_decode_u_64(raw[3]),
        );
      case 2:
        return const ReceiveResult_Err();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception("Expected 2 elements, got ${arr.length}");
    }
    return (dco_decode_String(arr[0]), dco_decode_String(arr[1]));
  }

  @protected
  SendResult dco_decode_send_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return SendResult_Ok(
          ticket: dco_decode_String(raw[1]),
          size: dco_decode_u_64(raw[2]),
        );
      case 1:
        return const SendResult_Err();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_record_string_string(deserializer);
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  RustStreamSink<List<ProgressState>>
  sse_decode_StreamSink_list_progress_state_Sse(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError("Unreachable ()");
  }

  @protected
  RustStreamSink<LogEntry> sse_decode_StreamSink_log_entry_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError("Unreachable ()");
  }

  @protected
  RustStreamSink<ReceiveResult> sse_decode_StreamSink_receive_result_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError("Unreachable ()");
  }

  @protected
  RustStreamSink<SendResult> sse_decode_StreamSink_send_result_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError("Unreachable ()");
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BlobInfo sse_decode_blob_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_size = sse_decode_u_64(deserializer);
    return BlobInfo(name: var_name, size: var_size);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<BlobInfo> sse_decode_list_blob_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BlobInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_blob_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ProgressState> sse_decode_list_progress_state(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ProgressState>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_progress_state(deserializer));
    }
    return ans_;
  }

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_string(deserializer));
    }
    return ans_;
  }

  @protected
  LogEntry sse_decode_log_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_time = sse_decode_u_64(deserializer);
    var var_level = sse_decode_String(deserializer);
    var var_target = sse_decode_String(deserializer);
    var var_data = sse_decode_Map_String_String_None(deserializer);
    return LogEntry(
      time: var_time,
      level: var_level,
      target: var_target,
      data: var_data,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Phase sse_decode_phase(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_name = sse_decode_String(deserializer);
        return Phase_Importing(name: var_name);
      case 1:
        var var_endpoint = sse_decode_String(deserializer);
        var var_isCompleted = sse_decode_bool(deserializer);
        var var_isFailed = sse_decode_bool(deserializer);
        return Phase_Uploading(
          endpoint: var_endpoint,
          isCompleted: var_isCompleted,
          isFailed: var_isFailed,
        );
      case 2:
        return const Phase_Pending();
      case 3:
        return const Phase_Connecting();
      case 4:
        return const Phase_Validating();
      case 5:
        return const Phase_Downloading();
      case 6:
        var var_name = sse_decode_String(deserializer);
        return Phase_Exporting(name: var_name);
      default:
        throw UnimplementedError("");
    }
  }

  @protected
  ProgressState sse_decode_progress_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_phase = sse_decode_phase(deserializer);
    var var_position = sse_decode_u_64(deserializer);
    var var_length = sse_decode_opt_box_autoadd_u_64(deserializer);
    return ProgressState(
      phase: var_phase,
      position: var_position,
      length: var_length,
    );
  }

  @protected
  ReceiveResult sse_decode_receive_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_files = sse_decode_list_blob_info(deserializer);
        return ReceiveResult_Pending(files: var_files);
      case 1:
        var var_totalFiles = sse_decode_u_64(deserializer);
        var var_payloadSize = sse_decode_u_64(deserializer);
        var var_elapsedSecs = sse_decode_u_64(deserializer);
        return ReceiveResult_Ok(
          totalFiles: var_totalFiles,
          payloadSize: var_payloadSize,
          elapsedSecs: var_elapsedSecs,
        );
      case 2:
        return const ReceiveResult_Err();
      default:
        throw UnimplementedError("");
    }
  }

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  SendResult sse_decode_send_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_ticket = sse_decode_String(deserializer);
        var var_size = sse_decode_u_64(deserializer);
        return SendResult_Ok(ticket: var_ticket, size: var_size);
      case 1:
        return const SendResult_Err();
      default:
        throw UnimplementedError("");
    }
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_string(
      self.entries.map((e) => (e.key, e.value)).toList(),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_list_progress_state_Sse(
    RustStreamSink<List<ProgressState>> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_progress_state,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_log_entry_Sse(
    RustStreamSink<LogEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_log_entry,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_receive_result_Sse(
    RustStreamSink<ReceiveResult> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_receive_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_send_result_Sse(
    RustStreamSink<SendResult> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_send_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_blob_info(BlobInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_u_64(self.size, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_blob_info(
    List<BlobInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_blob_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_progress_state(
    List<ProgressState> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_progress_state(item, serializer);
    }
  }

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_string(item, serializer);
    }
  }

  @protected
  void sse_encode_log_entry(LogEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.time, serializer);
    sse_encode_String(self.level, serializer);
    sse_encode_String(self.target, serializer);
    sse_encode_Map_String_String_None(self.data, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_phase(Phase self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case Phase_Importing(name: final name):
        sse_encode_i_32(0, serializer);
        sse_encode_String(name, serializer);
      case Phase_Uploading(
        endpoint: final endpoint,
        isCompleted: final isCompleted,
        isFailed: final isFailed,
      ):
        sse_encode_i_32(1, serializer);
        sse_encode_String(endpoint, serializer);
        sse_encode_bool(isCompleted, serializer);
        sse_encode_bool(isFailed, serializer);
      case Phase_Pending():
        sse_encode_i_32(2, serializer);
      case Phase_Connecting():
        sse_encode_i_32(3, serializer);
      case Phase_Validating():
        sse_encode_i_32(4, serializer);
      case Phase_Downloading():
        sse_encode_i_32(5, serializer);
      case Phase_Exporting(name: final name):
        sse_encode_i_32(6, serializer);
        sse_encode_String(name, serializer);
    }
  }

  @protected
  void sse_encode_progress_state(ProgressState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_phase(self.phase, serializer);
    sse_encode_u_64(self.position, serializer);
    sse_encode_opt_box_autoadd_u_64(self.length, serializer);
  }

  @protected
  void sse_encode_receive_result(ReceiveResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case ReceiveResult_Pending(files: final files):
        sse_encode_i_32(0, serializer);
        sse_encode_list_blob_info(files, serializer);
      case ReceiveResult_Ok(
        totalFiles: final totalFiles,
        payloadSize: final payloadSize,
        elapsedSecs: final elapsedSecs,
      ):
        sse_encode_i_32(1, serializer);
        sse_encode_u_64(totalFiles, serializer);
        sse_encode_u_64(payloadSize, serializer);
        sse_encode_u_64(elapsedSecs, serializer);
      case ReceiveResult_Err():
        sse_encode_i_32(2, serializer);
    }
  }

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_send_result(SendResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case SendResult_Ok(ticket: final ticket, size: final size):
        sse_encode_i_32(0, serializer);
        sse_encode_String(ticket, serializer);
        sse_encode_u_64(size, serializer);
      case SendResult_Err():
        sse_encode_i_32(1, serializer);
    }
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
