// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import "frb_generated.dart";
import "package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart";
import "package:freezed_annotation/freezed_annotation.dart" hide protected;
part "progresses.freezed.dart";

@freezed
sealed class Phase with _$Phase {
  const Phase._();

  const factory Phase.importing({required String name}) = Phase_Importing;
  const factory Phase.uploading({
    required String endpoint,
    required bool isCompleted,
    required bool isFailed,
  }) = Phase_Uploading;
  const factory Phase.pending() = Phase_Pending;
  const factory Phase.connecting() = Phase_Connecting;
  const factory Phase.validating() = Phase_Validating;
  const factory Phase.downloading() = Phase_Downloading;
  const factory Phase.exporting({required String name}) = Phase_Exporting;
}

class ProgressState {
  final Phase phase;
  final BigInt position;
  final BigInt? length;

  const ProgressState({
    required this.phase,
    required this.position,
    this.length,
  });

  @override
  int get hashCode => phase.hashCode ^ position.hashCode ^ length.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProgressState &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          position == other.position &&
          length == other.length;
}
