// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import "frb_generated.dart";
import "package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart";
import "package:freezed_annotation/freezed_annotation.dart" hide protected;
part "types.freezed.dart";

class BlobInfo {
  final String name;
  final BigInt size;

  const BlobInfo({required this.name, required this.size});

  @override
  int get hashCode => name.hashCode ^ size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BlobInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          size == other.size;
}

class LogEntry {
  final BigInt time;
  final String level;
  final String target;
  final Map<String, String> data;

  const LogEntry({
    required this.time,
    required this.level,
    required this.target,
    required this.data,
  });

  @override
  int get hashCode =>
      time.hashCode ^ level.hashCode ^ target.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LogEntry &&
          runtimeType == other.runtimeType &&
          time == other.time &&
          level == other.level &&
          target == other.target &&
          data == other.data;
}

@freezed
sealed class ReceiveResult with _$ReceiveResult {
  const ReceiveResult._();

  const factory ReceiveResult.pending({required List<BlobInfo> files}) =
      ReceiveResult_Pending;
  const factory ReceiveResult.ok({
    required BigInt totalFiles,
    required BigInt payloadSize,
    required BigInt elapsedSecs,
  }) = ReceiveResult_Ok;
  const factory ReceiveResult.err() = ReceiveResult_Err;
}

@freezed
sealed class SendResult with _$SendResult {
  const SendResult._();

  const factory SendResult.ok({required String ticket, required BigInt size}) =
      SendResult_Ok;
  const factory SendResult.err() = SendResult_Err;
}
